Controllers/adminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using gongshangchaxun.DAL;
using gongshangchaxun.Models;
using System.Data.OleDb;
using System.Transactions;
using System.Data.SqlClient;

namespace gongshangchaxun.Controllers
{   
    public class adminController : Controller
    { 
       private GongshangContent db = new GongshangContent();
        //
        // GET: /admin/
        [Authorize(Roles="manage")]
        public ActionResult Index()
        {
            return View( );
        }

        [Authorize(Roles = "manage")]
        public ActionResult listuser()
        {
            return View(db.userprofiles.ToList());
        }


        // GET: /Default1/Delete/5
        [Authorize(Roles = "manage")]
        public ActionResult Delete(int id = 0)
        {
            UserProfile userprofile = db.userprofiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
           
            return View(userprofile);
        }

        
        // POST: /Default1/Delete/5

        [HttpPost, ActionName("Delete")]
        
        [Authorize(Roles = "manage")]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.userprofiles.Find(id);
            using (TransactionScope transaction = new TransactionScope())
            {               
                string ConString = System.Configuration.ConfigurationManager.ConnectionStrings["GongshangContent"].ConnectionString;
                SqlConnection con = new SqlConnection(ConString);
                string sqldel1 = "delete from UserProfile where userid=' " + id.ToString() + "'";
                string sqldel2 = "delete from webpages_Membership where userid=' " + id.ToString() + "'";
                string sqldel3 = "delete from member where Username='" + userprofile.UserName + "'";
                try
                {
                    con.Open();

                    SqlCommand sqlcmddel = new SqlCommand(sqldel1, con);

                    sqlcmddel.ExecuteNonQuery();   //删除了姓名的名单


                    sqlcmddel = new SqlCommand(sqldel2, con);

                    sqlcmddel.ExecuteNonQuery();   //删除了密码的名单

                    sqlcmddel = new SqlCommand(sqldel3, con);

                    sqlcmddel.ExecuteNonQuery();   //删除了ftp用户的名单
                  
                }
                catch (Exception ex)
                {
                    ViewBag.error = ex.Message;
                    return View(); //返回错误描述
                }
                finally
                {
                    con.Close(); //无论如何都要执行的语句。
                }
                transaction.Complete();
            }
            return RedirectToAction("listuser");
    
          }


        public ActionResult setupcanshu() 
        {         
            return View(db.setupdbs.ToList());                 
        }


        [HttpPost]
        //[Authorize(Roles = "manage")]
     public ActionResult setupcanshu(FormCollection form)
         //  public ActionResult setupcanshu( setupdb setupdb)
        {
            

           string canshu=form["canshu"].ToString();
           string zhi = form["zhi"].ToString();
           
            string ConString = System.Configuration.ConfigurationManager.ConnectionStrings["GongshangContent"].ConnectionString;
            SqlConnection con = new SqlConnection(ConString);

            string insertstr = "insert into setupdb (canshu, zhi) values ('" + canshu + "','" + zhi + "' )";
            //  string insertstr = "insert into yichangmingdan (zhuceID, mingcheng, fadingdaibiaoren, jizaishiyou, jizairiqi, jizaibumen) values ('2000220022','dkfjgf','dfsfsdfs','dfsdfs','2009-10-10','fdsfsfdfd ')";
            SqlCommand cmd = new SqlCommand(insertstr, con);

            try
            {
                cmd.ExecuteNonQuery();
            }

            catch (Exception ex)
            {
                ViewBag.error = "第" +  "条名单插入有误，请认真检查格式后再导入！";

                return View();
            }

            finally
            {
                con.Close();
            }
            
            return View();        
            
        }

        
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        
    }
}

Views/admin/Delete.cshtml
@model gongshangchaxun.Models.UserProfile

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layoutgl.cshtml";
}

<div style="border-bottom:solid 1px #b5cbe3; margin-top:30px;">
         <div style=" float:left; padding-left:5px;font-size:18px; ">系统管理员——用户管理：</div>
         <div style="float:right;">
          <a href="/admin/"><img src="/content/images/fanhui.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:50px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
         </div>
         <div class="clr"></div>
     </div>

<p style="text-align:center; font-size:20px;">您确认要删除 @Html.DisplayFor(model => model.UserName) 吗？</p>


@*Html.BeginForm("delete", "admin", FormMethod.Post, new { enctype = "multipart/form-data" })*@
@using (Html.BeginForm()) {
    <p style="text-align:center;">
        <input type="submit" value="删除用户" style="font-size:20px;color:black;" /> 
    
    </p>
}

Views/admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layoutgl.cshtml";
}

<h3>企业信用查询系统——系统管理员操作：</h3>

<div class="glhomepage">
<table style="width: 60%;margin:auto; padding-top:60px; padding-bottom:60px;">
    <tr>
        <td><a href="/admin/listuser"><img src="/content/images/usergl1.png"   style="border:0" /></a></td>
        <td><a href="/test/index"><img src="/content/images/canshugl1.png"  style="border:0" /></a></td>
           </tr>
    
</table>
</div>

Views/admin/listuser.cshtml
@model IEnumerable<gongshangchaxun.Models.UserProfile>

@{
    ViewBag.Title = "listuser";
    Layout = "~/Views/Shared/_Layoutgl.cshtml";
}

@*<h3>企业信用查询系统——系统管理员操作：</h3>*@


<div style="border-bottom:solid 1px #b5cbe3; margin-top:30px;">
         <div style=" float:left; padding-left:5px;font-size:18px; ">系统管理员——用户管理：</div>
         <div style="float:right;">
          <a href="/admin/"><img src="/content/images/fanhui.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:50px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
         </div>
         <div class="clr"></div>
     </div>

<p style="text-align:center; font-size:26px;">
    @{ using (Html.BeginForm("register", "account", FormMethod.Get))
       {
           <input type="submit" value="创建新用户" style="font-size:20px;color:black;" />

                             }
    }
      
@*     @Html.ActionLink("创建新的管理员", "register" ,"account")*@
 </p>

<table class="tb3">
    <tr>
           <th style="width:20%;" >序号</th>
           <th style="width:40%;" >姓名</th>
           <th style="width:40%;">操作</th>
                 
    </tr>
    <tbody id="abnormalListBody">
            @{int xuhao = 0; }
            
            @foreach (var item in Model) {
              <tr>
                  <td>
                     @{ xuhao=xuhao+1;
                        @xuhao; }
                 </td>
                 <td>
                     @Html.DisplayFor(modelItem => item.UserName)
                 </td>
                 <td>
                     @{ if (item.UserName.ToString() == "admin")
                        {
                            <div>系统管理员，不能删除！</div>
                        }
                        else
                        { 
                         @Html.ActionLink("删除", "Delete", new { id=item.UserId })
                        }                                                
                         }
                    
                 </td>
                       
                 </tr>
             }
    </tbody>

</table>

Views/admin/setupcanshu.cshtml
@model IEnumerable<gongshangchaxun.Models.setupdb>

@{
    ViewBag.Title = "setupcanshu";
    Layout = "~/Views/Shared/_Layoutgl.cshtml";
}

@*<h3>企业信用查询系统——系统管理员操作：</h3>*@


<div style="border-bottom:solid 1px #b5cbe3; margin-top:30px;">
         <div style=" float:left; padding-left:5px;font-size:18px; ">系统管理员——参数管理：</div>
         <div style="float:right;">
          <a href="/admin/"><img src="/content/images/fanhui.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:50px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
         </div>
         <div class="clr"></div>
     </div>

@*<div style="color:red;">@ViewBag.error</div>*@

<fieldset>
        <legend>设置表单</legend>
     
        @Html.ActionLink("创建新的参数", "Create","admin")
         
 </fieldset>



    <fieldset style="padding-top:20px;">
        <legend>已设置的参数</legend>


        <table class="tb3">
         <tr>
           <th style="width:20%;" >序号</th>
           <th style="width:40%;" >参数</th>
           <th style="width:40%;">赋值</th>
                 
        </tr>
         <tbody id="abnormalListBody">
            @{int xuhao = 0; }
            
            @foreach (var item in Model) {
              <tr>
                  <td>
                     @{ xuhao=xuhao+1;
                        @xuhao; }
                 </td>
                 <td>
                     @Html.DisplayFor(ModelItem =>item.canshu)
                 </td>
                 <td>
                     @Html.DisplayFor(ModelItem =>item.zhi)
                              
                 </td>
                       
                 </tr>
             }
            </tbody>

        </table>
    </fieldset>
    