Models/dongchandiyaxinxi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace gongshangchaxun.Models
{
    public class dongchandiyaxinxi
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int dongchandiyaxinxiID { get; set; }


        [StringLength(50, ErrorMessage = "不能超过25个汉字。")]
        public string diyaren { get; set; }


        [StringLength(100, ErrorMessage = "不能超过25个汉字。")]
        public string dengjiID { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime dengjiriqi { get; set; }


        [StringLength(20, ErrorMessage = "不能超过10个汉字。")]
        public string dengjijiguan { get; set; }


        
        public decimal beidanbaozhaiquanshue { get; set; }


        



        [StringLength(300, ErrorMessage = "不能超过150个汉字。")]
        public string danbaofanwei { get; set; }


        [StringLength(100, ErrorMessage = "不能超过30个汉字。")]
        public string danbaoqixian { get; set; }


    }
}

Controllers/dongchandiyaxinxiController.cs
//using System;
//using System.Collections.Generic;
//using System.Data;
//using System.Data.Entity;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;
//using gongshangchaxun.Models;
//using gongshangchaxun.DAL;
using System;
using System.IO;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using gongshangchaxun.Models;
using gongshangchaxun.DAL;
using PagedList;
using System.Data.OleDb;
using System.Transactions;
using System.Data.SqlClient;

namespace gongshangchaxun.Controllers
{
    public class dongchandiyaxinxiController : Controller
    {
        private GongshangContent db = new GongshangContent();

        //
        // GET: /dongchandiyaxinxi/

        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            ViewBag.biaoti = "定安县动产抵押登记信息";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var dongchandiyaxinxis = from s in db.dongchandiyaxinxis
                               select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                dongchandiyaxinxis = dongchandiyaxinxis.Where(s => s.diyaren.ToUpper().Contains(searchString.ToUpper())
                                       || s.dengjiID.ToUpper().Contains(searchString.ToUpper()));


            }

            dongchandiyaxinxis = dongchandiyaxinxis.OrderByDescending(s => s.dengjiriqi);

            int pageSize = 10;

            int pageNumber = (page ?? 1);

            return View(dongchandiyaxinxis.ToPagedList(pageNumber, pageSize));
        }




        public ActionResult caozuoindex(string currentFilter, string searchString, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var dongchandiyaxinxis = from s in db.dongchandiyaxinxis
                               select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                dongchandiyaxinxis = dongchandiyaxinxis.Where(s => s.diyaren.ToUpper().Contains(searchString.ToUpper())
                                       || s.dengjiID.ToUpper().Contains(searchString.ToUpper()));

            }

            dongchandiyaxinxis = dongchandiyaxinxis.OrderByDescending(s => s.dengjiriqi);

            int pageSize = 10;

            int pageNumber = (page ?? 1);

            return View(dongchandiyaxinxis.ToPagedList(pageNumber, pageSize));
        }



        public FileResult GetFile()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory + "content/uploads/moban/";
            string fileName = "动产抵押登记信息.xlsx";
            return File(path + fileName, "text/plain", fileName);
        }






        [Authorize]
        public ActionResult excelImport()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult excelImport(FormCollection form)
        // public ActionResult excelImport(HttpPostedFileBase filebase)
        {
            ViewBag.error = "";
            // ViewBag.fugai = form["gengxinmoshi"].ToString();
            HttpPostedFileBase file = Request.Files["files"];
            //string file =form["files"];

            string FileName;
            string savePath;
            if (file == null || file.ContentLength <= 0)
            {
                ViewBag.error = "文件不能为空";
                return View();
            }
            else
            {
                string filename = Path.GetFileName(file.FileName);
                int filesize = file.ContentLength;//获取上传文件的大小单位为字节byte
                string fileEx = System.IO.Path.GetExtension(filename);//获取上传文件的扩展名
                string NoFileName = System.IO.Path.GetFileNameWithoutExtension(filename);//获取无扩展名的文件名

                //int Maxsize = 4000 * 1024;//定义上传文件的最大空间大小为4M

                string FileType = ".xls,.xlsx";//定义上传文件的类型字符串

                FileName = NoFileName + DateTime.Now.ToString("yyyyMMddhhmmss") + fileEx;
                if (!FileType.Contains(fileEx))
                {
                    ViewBag.error = "文件类型不对，只能导入xls和xlsx格式的文件";
                    return View();
                }

                string path = AppDomain.CurrentDomain.BaseDirectory + "content/uploads/excel/";
                savePath = Path.Combine(path, FileName);
                file.SaveAs(savePath);
            }

            //string result = string.Empty;
            string strConn;



            strConn = "Provider=Microsoft.Ace.OleDb.12.0;Data Source=" + savePath + ";" + "Extended Properties='Excel 12.0; HDR=Yes; IMEX=1'";

            OleDbConnection conn = new OleDbConnection(strConn);
            OleDbDataAdapter myCommand = new OleDbDataAdapter("select * from [Sheet1$]", strConn);
            DataSet myDataSet = new DataSet();
            try
            {
                conn.Open();
                myCommand.Fill(myDataSet, "ExcelInfo");

            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View(); //返回错误描述
            }
            finally
            {
                conn.Close(); //无论如何都要执行的语句。
            }

            DataTable ds = myDataSet.Tables["ExcelInfo"].DefaultView.ToTable();
            DataRow[] dr = ds.Select();


            //引用事务机制，出错时，事物回滚
            using (TransactionScope transaction = new TransactionScope())
            {
                if (form["gengxinmoshi"].ToString() == "fugai")
                {
                    string ConString = System.Configuration.ConfigurationManager.ConnectionStrings["GongshangContent"].ConnectionString;
                    SqlConnection con = new SqlConnection(ConString);
                    string sqldel = "delete from dongchandiyaxinxi";
                    try
                    {
                        con.Open();

                        SqlCommand sqlcmddel = new SqlCommand(sqldel, con);

                        sqlcmddel.ExecuteNonQuery();   //删除了现有的名单


                        int j;
                        for (int i = 0; i < dr.Length; i++)
                        {
                            j = i + 1;
                            string diyaren = dr[i]["抵押人名称（姓名）"].ToString();

                            string dengjiID = dr[i]["登记编号"].ToString();
                            string dengjiriqi = dr[i]["登记日期"].ToString();
                            string dengjijiguan = dr[i]["登记机关"].ToString();


                            string beidanbaozhaiquanshue = dr[i]["被担保债权数额"].ToString();
                            string danbaofanwei = dr[i]["担保的范围"].ToString();
                            string danbaoqixian = dr[i]["担保期限"].ToString();


                            string insertstr = "insert into dongchandiyaxinxi (diyaren, dengjiID, dengjiriqi, dengjijiguan, beidanbaozhaiquanshue, danbaofanwei, danbaoqixian) values ('" + diyaren + "','" + dengjiID + "','" + dengjiriqi + "','" + dengjijiguan + "','" + beidanbaozhaiquanshue + "','" + danbaofanwei + "','" + danbaoqixian + "')";

                            SqlCommand cmd = new SqlCommand(insertstr, con);
                            try
                            {
                                cmd.ExecuteNonQuery();
                            }

                            catch (Exception ex)
                            {
                                ViewBag.error = ex.ToString() + "第" + j + "条记录插入有误，请认真检查格式后再导入！";

                                return View();
                            }



                        }
                    }
                    catch (Exception ex)
                    {
                        ViewBag.error = ex.Message;
                        return View(); //返回错误描述
                    }
                    finally
                    {
                        con.Close(); //无论如何都要执行的语句。
                    }


                    //ViewBag.fugai = "离开覆盖了";
                }
                else  //追加模式
                {

                    string ConString = System.Configuration.ConfigurationManager.ConnectionStrings["GongshangContent"].ConnectionString;
                    SqlConnection con = new SqlConnection(ConString);

                    try
                    {
                        con.Open();
                        int j;
                        for (int i = 0; i < dr.Length; i++)
                        {
                            j = i + 1;
                            string diyaren = dr[i]["抵押人名称（姓名）"].ToString();

                            string dengjiID = dr[i]["登记编号"].ToString();
                            string dengjiriqi = dr[i]["登记日期"].ToString();
                            string dengjijiguan = dr[i]["登记机关"].ToString();


                            string beidanbaozhaiquanshue = dr[i]["被担保债权数额"].ToString();
                            string danbaofanwei = dr[i]["担保的范围"].ToString();
                            string danbaoqixian = dr[i]["担保期限"].ToString();


                            string insertstr = "insert into dongchandiyaxinxi (diyaren, dengjiID, dengjiriqi, dengjijiguan, beidanbaozhaiquanshue, danbaofanwei, danbaoqixian) values ('" + diyaren + "','" + dengjiID + "','" + dengjiriqi + "','" + dengjijiguan + "','" + beidanbaozhaiquanshue + "','" + danbaofanwei + "','" + danbaoqixian + "')";


                            SqlCommand cmd = new SqlCommand(insertstr, con);

                            try
                            {
                                cmd.ExecuteNonQuery();
                            }

Views/dongchandiyaxinxi/Create.cshtml
@model gongshangchaxun.Models.dongchandiyaxinxi

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>dongchandiyaxinxi</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.diyaren)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.diyaren)
            @Html.ValidationMessageFor(model => model.diyaren)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dengjiID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dengjiID)
            @Html.ValidationMessageFor(model => model.dengjiID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dengjiriqi)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dengjiriqi)
            @Html.ValidationMessageFor(model => model.dengjiriqi)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dengjijiguan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dengjijiguan)
            @Html.ValidationMessageFor(model => model.dengjijiguan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.beidanbaozhaiquanshue)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.beidanbaozhaiquanshue)
            @Html.ValidationMessageFor(model => model.beidanbaozhaiquanshue)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.danbaofangwei)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.danbaofangwei)
            @Html.ValidationMessageFor(model => model.danbaofangwei)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.danbaoqixian)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.danbaoqixian)
            @Html.ValidationMessageFor(model => model.danbaoqixian)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/dongchandiyaxinxi/Delete.cshtml
@model gongshangchaxun.Models.dongchandiyaxinxi

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>dongchandiyaxinxi</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.diyaren)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.diyaren)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dengjiID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dengjiID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dengjiriqi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dengjiriqi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dengjijiguan)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dengjijiguan)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.beidanbaozhaiquanshue)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.beidanbaozhaiquanshue)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.danbaofangwei)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.danbaofangwei)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.danbaoqixian)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.danbaoqixian)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/dongchandiyaxinxi/Details.cshtml
@model gongshangchaxun.Models.dongchandiyaxinxi

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>dongchandiyaxinxi</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.diyaren)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.diyaren)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dengjiID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dengjiID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dengjiriqi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dengjiriqi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dengjijiguan)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dengjijiguan)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.beidanbaozhaiquanshue)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.beidanbaozhaiquanshue)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.danbaofangwei)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.danbaofangwei)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.danbaoqixian)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.danbaoqixian)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.dongchandiyaxinxiID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/dongchandiyaxinxi/Edit.cshtml
@model gongshangchaxun.Models.dongchandiyaxinxi

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>dongchandiyaxinxi</legend>

        @Html.HiddenFor(model => model.dongchandiyaxinxiID)

        <div class="editor-label">
            @Html.LabelFor(model => model.diyaren)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.diyaren)
            @Html.ValidationMessageFor(model => model.diyaren)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dengjiID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dengjiID)
            @Html.ValidationMessageFor(model => model.dengjiID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dengjiriqi)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dengjiriqi)
            @Html.ValidationMessageFor(model => model.dengjiriqi)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dengjijiguan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.dengjijiguan)
            @Html.ValidationMessageFor(model => model.dengjijiguan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.beidanbaozhaiquanshue)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.beidanbaozhaiquanshue)
            @Html.ValidationMessageFor(model => model.beidanbaozhaiquanshue)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.danbaofangwei)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.danbaofangwei)
            @Html.ValidationMessageFor(model => model.danbaofangwei)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.danbaoqixian)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.danbaoqixian)
            @Html.ValidationMessageFor(model => model.danbaoqixian)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/dongchandiyaxinxi/Index.cshtml
@model PagedList.IPagedList<gongshangchaxun.Models.dongchandiyaxinxi>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title=ViewBag.biaoti;
}

<div class="listbox2"></div>
     <div class="listbox1">
         <div class="tle left">动产抵押登记信息：</div>
         <div class="right">
          @*   <a href="/yichangchaxun/excelImport/"><img src="/content/images/daoru.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:100px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>*@
             <a href="/"><img src="/content/images/fanhui.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:50px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
         </div>
         <div class="clr"></div>
     </div>
<table class="tablebox1">
    <tr>
        <th style="width:5%;">
            序号
        </th>
        <th style="line-height:30px;width:15%">
           抵押人名称(姓名)
        </th>
        <th style="width:15%;">
            登记编号
        </th>
        <th style="width:10%;">
            登记日期
        </th>
        <th style="width:12%;">
            登记机关
        </th>
        <th style="width:13%;">
            被担保债权数额
        </th>
        <th style="width:20%;">
            担保的范围
        </th>
        <th style="width:10%;">
            担保期限
        </th>
    </tr>

    <tbody id="abnormalListBody">
            @{int xuhao = 0; }
@foreach (var item in Model) {
    <tr>

         <td>
             @{ xuhao=xuhao+1;
                        @xuhao; }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.diyaren)
        </td>
        <td style="text-align:left;line-height:30px;">
            @Html.DisplayFor(modelItem => item.dengjiID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dengjiriqi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dengjijiguan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.beidanbaozhaiquanshue)
        </td>
        <td style="text-align:left;line-height:30px;">
            @Html.DisplayFor(modelItem => item.danbaofanwei)
        </td>
        <td style="text-align:left;line-height:30px;">
            @Html.DisplayFor(modelItem => item.danbaoqixian)
        </td>
    </tr>
}
         </tbody>
</table>
<br />
<div style="text-align:right; margin-right:100px">
@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount 页

@Html.PagedListPager( Model, page => Url.Action("Index", new { page, currentFilter=ViewBag.CurrentFilter }) )
    
</div> 

Views/dongchandiyaxinxi/caozuoindex.cshtml
@model PagedList.IPagedList<gongshangchaxun.Models.dongchandiyaxinxi>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "动产抵押信息";
    Layout = "~/Views/Shared/_Layoutgl.cshtml";
} 
    <div class="listbox2"></div>
     <div class="listbox1">
         <div class="tle left">动产抵押登记信息：</div>
         <div class="right">
             <a href="/dongchandiyaxinxi/excelImport/"><img src="/content/images/daoru.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:100px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
             <a href="/gl/"><img src="/content/images/fanhui.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:50px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
         </div>
         <div class="clr"></div>
     </div>


@{  string init_search="";
    if (ViewBag.CurrentFilter == null)

    { init_search = " "; }
    
   
    else
   {
      init_search=ViewBag.CurrentFilter;
    }
 }


@using (Html.BeginForm( ))
{
    <table id="mytable2" >
        <tr>
          <td style="width:60%; text-align:right; ">
              <input type="text" id="name" name="SearchString" style="width:500px;height:33px;line-height:30px;" value="@init_search" onfocus="if(this.value==defaultValue){this.value='';}" onblur="if(!value){this.value=defaultValue;}" />
          </td>
          <td style="width:40%;margin-left:1px;" >
              <input type="submit" value=""  class="btn_s_index" />
          </td>
        </tr>
      </table>    
}

<table class="tablebox1">
     <tr>
        <th style="width:5%;">
            序号
        </th>
        <th style="line-height:30px;width:15%">
           抵押人名称(姓名)
        </th>
        <th style="width:12%;">
            登记编号
        </th>
        <th style="width:7%;">
            登记日期
        </th>
        <th style="width:15%;">
            登记机关
        </th>
        <th style="width:13%;">
            被担保债权数额
        </th>
        <th style="width:23%;">
            担保的范围
        </th>
        <th style="width:10%;">
            担保期限
        </th>
    </tr>

    <tbody id="abnormalListBody">
            @{int xuhao = 0; }
@foreach (var item in Model) {
    <tr>

        <td>
             @{ xuhao=xuhao+1;
                        @xuhao; }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.diyaren)
        </td>
        <td style="text-align:left;line-height:30px;">
            @Html.DisplayFor(modelItem => item.dengjiID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dengjiriqi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dengjijiguan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.beidanbaozhaiquanshue)
        </td>
        <td style="text-align:left;line-height:30px;">
            @Html.DisplayFor(modelItem => item.danbaofanwei)
        </td>
        <td style="text-align:left;line-height:30px;">
            @Html.DisplayFor(modelItem => item.danbaoqixian)
        </td>

    </tr>
}
         </tbody>
</table>
<br />
<div style="text-align:right; margin-right:100px">
@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount 页

@Html.PagedListPager( Model, page => Url.Action("Index", new { page, currentFilter=ViewBag.CurrentFilter }) )
    
</div>   

Views/dongchandiyaxinxi/excelImport.cshtml
@{
    ViewBag.Title = "动产抵押信息";
}

@using (Html.BeginForm("excelImport", "dongchandiyaxinxi", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    
    <div class="listbox2"></div>
     <div class="listbox1">
         <div class="tle left">动产抵押登记信息批量导入：</div>
         <div class="right">
             <a href="/dongchandiyaxinxi/caozuoindex"><img src="/content/images/back.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:100px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
         </div>
         <div class="clr"></div>
     </div>           
    <div>
        <fieldset id="myfieldset">
            <legend>Excel模版格式 </legend>
            <p style="text-align: center;"><img src="~/content/images/download.png" style="width:30px;height:30px;vertical-align:middle;"/>导入的模板格式如下，若模板格式不正确，则相应的名单不能导入:</p>
           
            <p style="color: Red; text-align: center;"> @Html.ActionLink("下载模版", "GetFile")</p>
        </fieldset>
    </div>
    <div style="margin-top: 20px;">
        <fieldset id="myfieldset1">
            <legend>批量信息导入</legend>
            <p style="margin-left:550px; font-size:18px;font-weight:bold;">
                选择文件：<input id="FileUpload" type="file" name="files" style="width: 250px; height: 24px;
                    background: White" class="easyui-validatebox" /></p>
             <p style="margin-left:550px; font-size:18px;font-weight:bold;">
                更新模式：<select id="gengxinmoshi" name="gengxinmoshi">
                                <option value ="zhuijia">追加</option>
                                 <option value ="fugai">覆盖</option>
                         
                          </select>
                                                  </p>
            <p style="text-align: center;">
                <input id="btnImport" type="submit" value="导入" style="width: 60px; height: 28px; color:black;" /></p>
            <p style="color: Red; text-align: center;">@ViewBag.error</p>
        </fieldset>
    </div>
}