Controllers/yichangchaxunController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using gongshangchaxun.Models;
using gongshangchaxun.DAL;
using PagedList;
using System.Data.OleDb;
using System.Transactions;
using System.Data.SqlClient;
//using System.Data;

namespace gongshangchaxun.Controllers
{
    public class yichangchaxunController : Controller
    {
        private GongshangContent db = new GongshangContent();

        //
        // GET: /yichangchaxun/

        public ActionResult Index(string currentFilter, string searchString, int? page)
        {   
            ViewBag.biaoti = "县企业异常名录公示与查询";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var yichangmingdans = from s in db.yichangmingdans
                                  select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                yichangmingdans = yichangmingdans.Where(s => s.zhuceID.ToUpper().Contains(searchString.ToUpper())
                                       || s.mingcheng.ToUpper().Contains(searchString.ToUpper()) || s.fadingdaibiaoren.ToUpper().Contains(searchString.ToUpper()) || s.zuochujuedingjiguan.Contains(searchString));
                            }

            yichangmingdans = yichangmingdans.OrderByDescending(s => s.lieruriqi);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
          
            return View(yichangmingdans.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult caozuoindex(string currentFilter, string searchString, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            var yichangmingdans = from s in db.yichangmingdans
                                  select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                yichangmingdans = yichangmingdans.Where(s => s.zhuceID.ToUpper().Contains(searchString.ToUpper())
                                       || s.mingcheng.ToUpper().Contains(searchString.ToUpper()) || s.fadingdaibiaoren.ToUpper().Contains(searchString.ToUpper()) || s.zuochujuedingjiguan.Contains(searchString));

            }

            yichangmingdans = yichangmingdans.OrderByDescending(s => s.lieruriqi);

            int pageSize = 10;

            int pageNumber = (page ?? 1);

            return View(yichangmingdans.ToPagedList(pageNumber, pageSize));
        
        
        }

        public FileResult GetFile()
        {
            string path = AppDomain.CurrentDomain.BaseDirectory + "content/uploads/moban/";
            string fileName = "异常企业名录.xls";
            return File(path + fileName, "text/plain", fileName);
        }


       [Authorize]
        public ActionResult excelImport()
        {
            return View();
        }
      
        [HttpPost]
        [Authorize]
       public ActionResult excelImport(FormCollection form)
      // public ActionResult excelImport(HttpPostedFileBase filebase)
        {
            ViewBag.error = "";
           // ViewBag.fugai = form["gengxinmoshi"].ToString();
            HttpPostedFileBase file = Request.Files["files"];
            //string file =form["files"];

            string FileName;
            string savePath;
            if (file == null || file.ContentLength <= 0)
            {
                ViewBag.error = "文件不能为空";
                return View();
            }
            else
            {
                string filename = Path.GetFileName(file.FileName);
                int filesize = file.ContentLength;//获取上传文件的大小单位为字节byte
                string fileEx = System.IO.Path.GetExtension(filename);//获取上传文件的扩展名
                string NoFileName = System.IO.Path.GetFileNameWithoutExtension(filename);//获取无扩展名的文件名

                //int Maxsize = 4000 * 1024;//定义上传文件的最大空间大小为4M

                string FileType = ".xls,.xlsx";//定义上传文件的类型字符串

                FileName = NoFileName + DateTime.Now.ToString("yyyyMMddhhmmss") + fileEx;
                if (!FileType.Contains(fileEx))
                {
                    ViewBag.error = "文件类型不对，只能导入xls和xlsx格式的文件";
                    return View();
                }
                //if (filesize >= Maxsize)
                //{
                //    ViewBag.error = "上传文件超过4M，不能上传";
                //    return View();
                //}
                string path = AppDomain.CurrentDomain.BaseDirectory + "content/uploads/excel/";
                savePath = Path.Combine(path, FileName);
                file.SaveAs(savePath);
            }

            //string result = string.Empty;
            string strConn;


            //office 2007 可用 导入xls 不用于.xlsx
              //strConn = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + savePath + ";" + "Extended Properties=Excel 8.0";

             strConn="Provider=Microsoft.Ace.OleDb.12.0;Data Source="+ savePath +";"+"Extended Properties='Excel 12.0; HDR=Yes; IMEX=1'";

            OleDbConnection conn = new OleDbConnection(strConn);
            OleDbDataAdapter myCommand = new OleDbDataAdapter("select * from [Sheet1$]", strConn);
            DataSet myDataSet = new DataSet();
            try
            {
                conn.Open();
                myCommand.Fill(myDataSet, "ExcelInfo");

            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View(); //返回错误描述
            }
            finally
            {
                conn.Close(); //无论如何都要执行的语句。
            }
                                
            DataTable ds = myDataSet.Tables["ExcelInfo"].DefaultView.ToTable();
            DataRow[] dr = ds.Select();
            
           
            //引用事务机制，出错时，事物回滚
            using (TransactionScope transaction = new TransactionScope())
            {
                if (form["gengxinmoshi"].ToString() == "fugai")
                {
                    string ConString = System.Configuration.ConfigurationManager.ConnectionStrings["GongshangContent"].ConnectionString;
                    SqlConnection con = new SqlConnection(ConString); 
                    string sqldel = "delete from yichangmingdan";
                    try
                    {
                        con.Open();                                                     

                        SqlCommand sqlcmddel = new SqlCommand(sqldel, con);

                        sqlcmddel.ExecuteNonQuery();   //删除了现有的名单


                        int j;
                        for (int i = 0; i < dr.Length; i++)
                        {
                            j = i + 1;
                            string zhuceID = dr[i]["注册号"].ToString();
                            string mingcheng = dr[i]["企业名称"].ToString();
                            string fadingdaibiaoren = dr[i]["法定代表人"].ToString();
                            string lieruriqi = dr[i]["列入日期"].ToString();
                            string lierushiyou = dr[i]["列入事由"].ToString();

                            string zuochujuedingjiguan1 = dr[i][6].ToString(); //"作出决定机关"

                            string yichuriqi = dr[i]["移出日期"].ToString();
                            string yichushiyou = dr[i]["移出事由"].ToString();

                            string zuochujuedingjiguan = dr[i][9].ToString(); //"作出决定机关"


                            //string insertstr = "insert into yichangmingdan (zhuceID, mingcheng, fadingdaibiaoren, lieruriqi,lierushiyou, yichuriqi, yichushiyou, zuochujuedingjiguan) values ('" + zhuceID + "','" + mingcheng + "','" + fadingdaibiaoren + "','" + lieruriqi + "','" + lierushiyou + "','" + yichuriqi + "','" + tempriqi + "','" + zuochujuedingjiguan + "' )";   "tempriqi"是什么
                                string insertstr = "insert into yichangmingdan (zhuceID, mingcheng, fadingdaibiaoren, lieruriqi,lierushiyou,zuochujuedingjiguan1, yichuriqi, yichushiyou, zuochujuedingjiguan) values ('" + zhuceID + "','" + mingcheng + "','" + fadingdaibiaoren + "','" + lieruriqi + "','" + lierushiyou + "','" + zuochujuedingjiguan1 + "','" + yichuriqi + "','" + yichushiyou + "','" + zuochujuedingjiguan + "' )";
                                //  string insertstr = "insert into yichangmingdan (zhuceID, mingcheng, fadingdaibiaoren, jizaishiyou, jizairiqi, jizaibumen) values ('2000220022','dkfjgf','dfsfsdfs','dfsdfs','2009-10-10','fdsfsfdfd ')";
                                SqlCommand cmd = new SqlCommand(insertstr, con);
                                try
                                {
                                    cmd.ExecuteNonQuery();
                                }

                                catch (Exception ex )
                                {
                                    ViewBag.error = ex.ToString() + "第" + j + "条记录插入有误，请认真检查格式后再导入！";

                                    return View();
                                }

                        }
                    }
                    catch (Exception ex)
                    {
                        ViewBag.error = ex.Message;
                        return View(); //返回错误描述
                    }
                    finally
                    {
                        con.Close(); //无论如何都要执行的语句。
                    }          

                       
                   //ViewBag.fugai = "离开覆盖了";
                }
                else  //追加模式
                {
                    
                    string ConString = System.Configuration.ConfigurationManager.ConnectionStrings["GongshangContent"].ConnectionString;

Views/yichangchaxun/Create.cshtml
@model gongshangchaxun.Models.yichangmingdan

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>yichangmingdan</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.mingcheng)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.mingcheng)
            @Html.ValidationMessageFor(model => model.mingcheng)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.fadingdaibiaoren)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.fadingdaibiaoren)
            @Html.ValidationMessageFor(model => model.fadingdaibiaoren)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.jizaishiyou)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.jizaishiyou)
            @Html.ValidationMessageFor(model => model.jizaishiyou)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.jizairiqi)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.jizairiqi)
            @Html.ValidationMessageFor(model => model.jizairiqi)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.jizaibumen)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.jizaibumen)
            @Html.ValidationMessageFor(model => model.jizaibumen)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/yichangchaxun/Delete.cshtml
@model gongshangchaxun.Models.yichangmingdan

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>yichangmingdan</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.mingcheng)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.mingcheng)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.fadingdaibiaoren)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.fadingdaibiaoren)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.jizaishiyou)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.jizaishiyou)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.jizairiqi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.jizairiqi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.jizaibumen)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.jizaibumen)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/yichangchaxun/Details.cshtml
@model gongshangchaxun.Models.yichangmingdan

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>yichangmingdan</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.mingcheng)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.mingcheng)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.fadingdaibiaoren)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.fadingdaibiaoren)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.jizaishiyou)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.jizaishiyou)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.jizairiqi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.jizairiqi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.jizaibumen)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.jizaibumen)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.zhuceID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/yichangchaxun/Edit.cshtml
@model gongshangchaxun.Models.yichangmingdan

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>yichangmingdan</legend>

        @Html.HiddenFor(model => model.zhuceID)

        <div class="editor-label">
            @Html.LabelFor(model => model.mingcheng)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.mingcheng)
            @Html.ValidationMessageFor(model => model.mingcheng)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.fadingdaibiaoren)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.fadingdaibiaoren)
            @Html.ValidationMessageFor(model => model.fadingdaibiaoren)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.jizaishiyou)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.jizaishiyou)
            @Html.ValidationMessageFor(model => model.jizaishiyou)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.jizairiqi)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.jizairiqi)
            @Html.ValidationMessageFor(model => model.jizairiqi)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.jizaibumen)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.jizaibumen)
            @Html.ValidationMessageFor(model => model.jizaibumen)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/yichangchaxun/Index.cshtml
@model PagedList.IPagedList<gongshangchaxun.Models.yichangmingdan>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title=ViewBag.biaoti;
} 
    <div class="listbox2"></div>
     <div class="listbox1">
         <div class="tle left">企业经营异常名录信息：</div>
         <div class="right">
             <a href="/"><img src="/content/images/fanhui.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:50px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
         </div>
         <div class="clr"></div>
     </div>
@{  string init_search="";
    if (ViewBag.CurrentFilter == null)
    { init_search = " "; }//搜索框的初始值      
    else
   {
      init_search=ViewBag.CurrentFilter;
    }
 }

@using (Html.BeginForm( ))
{
    <table id="mytable2" >
        <tr>
          <td style="width:60%; text-align:right; ">
              <input type="text" id="name" name="SearchString" style="width:500px;height:33px;line-height:30px;" value="@init_search" onfocus="if(this.value==defaultValue){this.value='';}" onblur="if(!value){this.value=defaultValue;}" />
          </td>
          <td style="width:40%;margin-left:1px;" >
              <input type="submit" value=""  class="btn_s_index" />
          </td>
        </tr>
      </table>    
}


<table class="tablebox1" >
    <tr>                
           <th style="width:5%;" >序号</th>
           <th style="width:11%;" >注册号</th>
           <th style="width:17%;">企业名称</th>
           
           <th style="width:7%;">法定代表人</th>
           <th style="width:7%;">列入日期</th>
           <th style="width:14%;">列入事由</th>
           <th style="width:9%;">作出决定机关</th>
           <th style="width:7%;">移出日期</th>
           <th style="width:14%;">移出事由</th>
           <th style="width:9%;">作出决定机关</th>
    </tr>
    <tbody id="abnormalListBody">
            @{int xuhao = 0; }
            
            @foreach (var item in Model) {
              <tr>
                  <td>
                     @{ xuhao=xuhao+1;
                        @xuhao; }
                 </td>
                 <td>
                     @Html.DisplayFor(modelItem => item.zhuceID)
                 </td>
                 <td>
                      @Html.DisplayFor(modelItem => item.mingcheng)
                 </td>
                 <td>
                      @Html.DisplayFor(modelItem => item.fadingdaibiaoren)
                 </td>
                 <td >
                      @Html.DisplayFor(modelItem => item.lieruriqi )
                 </td>
                 <td style="text-align:left;line-height:30px;">
                      @Html.DisplayFor(modelItem => item.lierushiyou )
                 </td>
                  <td>
                      @Html.DisplayFor(modelItem => item.zuochujuedingjiguan1 )
                  </td>
                  <td>
                      @Html.DisplayFor(modelItem => item.yichuriqi )
                  </td>
                   <td style="text-align:left;line-height:30px;">
                      @Html.DisplayFor(modelItem => item.yichushiyou )
                  </td>
                   <td>
                      @Html.DisplayFor(modelItem => item.zuochujuedingjiguan )
                  </td>
                 </tr>
             }
    </tbody>

</table>
<br />
<div style="text-align:right; margin-right:100px">
@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount 页
@Html.PagedListPager( Model, page => Url.Action("Index", new { page, currentFilter=ViewBag.CurrentFilter }) )      
</div>

Views/yichangchaxun/caozuoindex.cshtml
@model PagedList.IPagedList<gongshangchaxun.Models.yichangmingdan>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "企业异常名录公示与查询";
    Layout = "~/Views/Shared/_Layoutgl.cshtml";
} 
    <div class="listbox2"></div>
     <div class="listbox1">
         <div class="tle left">企业经营异常名录信息：</div>
         <div class="right">
             <a href="/yichangchaxun/excelImport/"><img src="/content/images/daoru.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:100px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
             <a href="/gl/"><img src="/content/images/fanhui.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:50px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
         </div>
         <div class="clr"></div>
     </div>
  
@{  string init_search="";
    if (ViewBag.CurrentFilter == null)
    { init_search = " "; }       
    else
   {
      init_search=ViewBag.CurrentFilter;
    }
 }
@using (Html.BeginForm( ))
{
    <table id="mytable2" >
        <tr>
          <td style="width:60%; text-align:right; ">
              <input type="text" id="name" name="SearchString" style="width:500px;height:33px;line-height:30px;" value="@init_search" onfocus="if(this.value==defaultValue){this.value='';}" onblur="if(!value){this.value=defaultValue;}" />
          </td>
          <td style="width:40%;margin-left:1px;" >
              <input type="submit" value=""  class="btn_s_index" />
          </td>
        </tr>
      </table>    
}


<table class="tablebox1">
    <tr>         
            <th style="width:5%;" >序号</th>
           <th style="width:11%;" >注册号</th>
           <th style="width:17%;">企业名称</th>           
           <th style="width:7%;">法定代表人</th>
           <th style="width:7%;">列入日期</th>
           <th style="width:14%;">列入事由</th>
           <th style="width:9%;">作出决定机关</th>
           <th style="width:7%;">移出日期</th>
           <th style="width:14%;">移出事由</th>
           <th style="width:9%;">作出决定机关</th>
    </tr>
    <tbody id="abnormalListBody">
            @{int xuhao = 0; }
            
            @foreach (var item in Model) {
              <tr>
                  <td>
                     @{ xuhao=xuhao+1;
                        @xuhao; }
                 </td>
                 <td>
                     @Html.DisplayFor(modelItem => item.zhuceID)
                 </td>
                 <td>
                      @Html.DisplayFor(modelItem => item.mingcheng)
                 </td>
                 <td>
                      @Html.DisplayFor(modelItem => item.fadingdaibiaoren)
                 </td>
                 <td >
                      @Html.DisplayFor(modelItem => item.lieruriqi )
                 </td>
                 <td style="text-align:left;line-height:30px;">
                      @Html.DisplayFor(modelItem => item.lierushiyou )
                 </td>
                  <td>
                      @Html.DisplayFor(modelItem => item.zuochujuedingjiguan1 )
                  </td>
                  <td>
                      @Html.DisplayFor(modelItem => item.yichuriqi )
                  </td>
                   <td style="text-align:left;line-height:30px;">
                      @Html.DisplayFor(modelItem => item.yichushiyou )
                  </td>
                   <td>
                      @Html.DisplayFor(modelItem => item.zuochujuedingjiguan )
                  </td>
       
                 </tr>
             }
    </tbody>

</table>
<br />
<div style="text-align:right; margin-right:100px">
@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount 页
@Html.PagedListPager( Model, page => Url.Action("Index", new { page, currentFilter=ViewBag.CurrentFilter }) )       
</div>

Views/yichangchaxun/excelImport.cshtml
@{
    ViewBag.Title = "定安县企业经营异常名单";
}
@using (Html.BeginForm("excelImport", "yichangchaxun", FormMethod.Post, new { enctype = "multipart/form-data" }))
{    
    <div class="listbox2"></div>
     <div class="listbox1">
         <div class="tle left">企业经营异常名单批量导入：</div>
         <div class="right">
             <a href="/yichangchaxun/caozuoindex"><img src="/content/images/back.png" style="float:right; margin-top:1px; margin-bottom:2px; margin-right:100px; cursor: pointer;border-width:0px 0px 0px 0px;height:30px;"/></a>
         </div>
         <div class="clr"></div>
     </div>
    <div>
        <fieldset id="myfieldset">
            <legend>Excel模版格式 </legend>
            <p style="text-align: center;"><img src="~/content/images/download.png" style="width:30px;height:30px;vertical-align:middle;"/>导入的模板格式如下，若模板格式不正确，则相应的名单不能导入:</p>
           
            <p style="color: Red; text-align: center;"> @Html.ActionLink("下载模版", "GetFile")</p>
        </fieldset>
    </div>
    <div style="margin-top: 20px;">
        <fieldset id="myfieldset1">
            <legend>批量信息导入</legend>
            <p style="margin-left:550px; font-size:18px;font-weight:bold;">
                选择文件：<input id="FileUpload" type="file" name="files" style="width: 250px; height: 24px;
                    background: White" class="easyui-validatebox" /></p>
             <p style="margin-left:550px; font-size:18px;font-weight:bold;">
                更新模式：<select id="gengxinmoshi" name="gengxinmoshi">
                                <option value ="zhuijia">追加</option>
                                 <option value ="fugai">覆盖</option>                         
                          </select>
                                                  </p>
            <p style="text-align: center;">
                <input id="btnImport" type="submit" value="导入" style="width: 60px; height: 28px; color:black;" /></p>
            <p style="color: Red; text-align: center;">@ViewBag.error</p>
        </fieldset>
    </div>
}